### ISSUE TITLE
[FEATURE] Odin Serializer Integration

### ISSUE THREAD

**Issue by daneobyrd** [unity-atoms/unity-atoms#291]
**Is your feature request related to a problem? Please describe.**
I read the following under "**Q: What will the future of Unity Atoms be?**" in the FAQ.

> Currently Unity Atoms is really pushing the use of generics to its limits in order to please Unity's serializer. This makes it unnecessarily hard to introduce new features to the library. If the API (generic signature) is breaking between major releases it makes it difficult for users to upgrade.
> 
> Unity 2020 will support serialization of generic fields. Unity Atoms could shave off a good chunk of the source code and make the library more sustainable by embracing this new feature.

**Describe the solution you'd like**
While Unity's serialization is simple and straightforward, I wondered whether [Odin Serializer](https://github.com/TeamSirenix/odin-serializer) (which is open-source) would help.

**Describe alternatives you've considered**
I lack the experience to truly understand all the nuances of each approach to serialization. However, with Unity 2020 supporting serialization of generic fields and Unity 2021 introducing a new [ObjectPool](https://docs.unity3d.com/2021.1/Documentation/ScriptReference/Pool.IObjectPool_1.html) [API](https://docs.unity3d.com/Packages/com.unity.render-pipelines.core@12.0/api/UnityEngine.Rendering.ObjectPool-1.html), I assume there are alternatives.

**Additional context**
Here are some words of caution Odin Serializer provides you upon installation.
> Odin's custom serialization protocol is stable and fast. It is built to be fast, reliable and resilient above all.
> 
> *Words of caution*
> However, caveats apply - there is a reason Unity chose such a drastically limited serialization protocol. It keeps things simple and manageable, and limits how much complexity you can introduce into your data structures. It can be very easy to get carried away and shoot yourself in the foot when all limitations suddenly disappear, and hence we have included this cautionary warning.
> 
> Warning words aside, there can of course be valid reasons to use a more powerful serialization protocol such as Odin's. However, we advise you to use it wisely and with restraint. After all, with great power comes great responsibility.

**Comment by simonbucher** [comment]
The features of Odin serializer are pretty nice. I wanted to use it for serializing dictionaries in a mobile game. Sadly it was not a suitable solution. 

For mobile games, Odin serializer increases load time.

**Comment by simonbucher** [comment]
Odin Serializer also increased the build size for a couple of MBs. In mobile games every MB counts.

I strongly recommend not using Odin Serializer. For me it would be a deal breaker for using unity-atoms in mobile games =(

**Comment by daneobyrd** [comment]
> Odin Serializer also increased the build size for a couple of MBs. In mobile games every MB counts.
> 
> I strongly recommend not using Odin Serializer. For me it would be a deal breaker for using unity-atoms in mobile games =(

Hopefully that’s not the case for me because my serialized dictionary is a dictionary of serializable scriptable objects. It should be fine as I can cut back on build size elsewhere.

Either way I do like many of the ways they extend Unity’s serialization protocol. I was wondering whether some of their approaches would prove useful for atom’s needs.

**Comment by tarragonfly** [comment]
Odin Serializer does not support nested prefabs. See serialized dictionaries not working properly in a nested prefab and the asset warning you about that. Wouldn't this also limit atoms usage in that context?

Adding a couple of megabytes to build size is also a non starter since you don't even get any of the Odin Inspector benefits with the open source serializer. 

Imo it would be best for Atoms to stay native.

**Comment by soraphis** [comment]
closing this for several reasons:
- there is no feature that Odin Serializer would give that is desperately needed to make atoms work
- while Odin Serializer is open source it's still a third party dependency we don't need
   - it has no easy way to install it as a dependency (not installable via openUPM or likewise (at least not the official source))
- other drawbacks mentioned above
- staleness. this issue is from 2021 and has not seen any upvotes or comments of the community, so even if wished it does not seem to have a high priority.


feel free to reopen
