### ISSUE TITLE
[QUESTION] How to create an action with a flexible parameter that modifies a value list?

### ISSUE THREAD

**Issue by jtuchel** [unity-atoms/unity-atoms#351]
**State your question below**
This package is new to me and I would like to play around with it by creating a Tic Tac Toe game. I created an enum holding the state of a square

```cs
public enum SquareState
{
    Neutral,
    MarkedByPlayer,
    MarkedByAi
}
```

and generated a new atom template via

```
using System;

[Serializable]
public struct Square
{
    public SquareState State;
}
```

I want to work with a one dimensional board, so I think a value list is the right one to pick

![image](https://user-images.githubusercontent.com/92626738/167290288-14f543be-fb06-44f7-b582-a42401eb6e09.png)

Now inside the UI I have 9 buttons where each button represents one square by its index. I don't know how to create an action that takes in the button index ( int field ), the squares value list variable and runs something like `list[index] = SquareState.MarkedByPlayer`. Because currently I only know how to create actions without parameters.

It would be awesome if someone would explain how to create such a flexible action ( still a simple usecase I think ) or how to solve it using different approaches.

Or should I create a normal Monobehaviour script? I tried this

```cs
using UnityAtoms;
using UnityEngine;

public sealed class MarkSquareByPlayer : MonoBehaviour
{
    [SerializeField]
    private SquareValueList squares;
    
    [SerializeField]
    private int squareIndex;
    
    public void Do()
    {
        squares[squareIndex].State = SquareState.MarkedByPlayer;
    }
}
```

but unforuntately I get the error

> Indexer access returns temporary value. Cannot modify struct member when accessed struct is not classified as a variable

Thanks in advance!

**Comment by niscolas** [comment]
The Atom Action class has a `Do()` method without parameters, I believe that you could use it. 

```csharp
using UnityAtoms;
using UnityEngine;

public sealed class MarkSquareByPlayerAtomAction : AtomAction<Void>
{
    [SerializeField]
    private SquareValueList squares;
    
    [SerializeField]
    private int squareIndex;
    
    public void Do(Void value)
    {
        Do();
    }
    
    public void Do()
    {
        squares[squareIndex].State = SquareState.MarkedByPlayer;
    }
}
```

Besides you could also use the `Do(value)` overload too.

```csharp
using UnityAtoms;
using UnityEngine;

public sealed class MarkSquareByPlayerAtomAction : AtomAction<int>
{
    [SerializeField]
    private SquareValueList squares;
    
    [SerializeField]
    private int squareIndex;
    
    public void Do()
    {
        Do(squareIndex);
    }
    
    public void Do(int value)
    {
        squares[squareIndex].State = value;
    }
}
```

Don't know if that answers your question :sweat_smile:

**Comment by soraphis** [comment]
> Because currently I only know how to create actions without parameters.

use AtomAction<T> (https://github.com/unity-atoms/unity-atoms/blob/master/Packages/Core/Runtime/Actions/AtomAction.cs#L21=) as your base class, instead of AtomAction. 

that way, you can pass an argument.

> I don't know how to create an action that takes in the button index ( int field ), the squares value list variable and runs something like list[index] = SquareState.MarkedByPlayer. 

when opening your UI take the `SquareValueList squares;` Count to create enough buttons. when constructing these buttons pass them their index to some kind of monobehaviour which will invoke the action


> but unforuntately I get the error
> Indexer access returns temporary value. Cannot modify struct member when accessed struct is not classified as a variable

I can only recommend Jetbrains Rider as an IDE. Yes it's a commercial IDE and I can see that it might be an expensive payment (just note, that they have a perpetual license, so you can leave it at an one-time-payment).

to solve the error: 
change `        squares[squareIndex].State = SquareState.MarkedByPlayer;`
to:
```
        var tmp = squares[squareIndex];
        tmp.State = SquareState.MarkedByPlayer;
        squares[squareIndex] = tmp; 
```

the error tells you that the indexer (`squares[squareIndex]`) returns a temporary value (a copy, not a reference to the actual object). so any modifications you do on top of it, just influence the copy.
in this case i gave the copy a name `tmp`, which solves the issue.

**Comment by soraphis** [comment]
closed because of inactivity.
if your question was not answered, feel free to reopen
