### ISSUE TITLE
[BUG] Vector2/3 reference not properly showing in unity editor.

### ISSUE THREAD

**Issue by SeeSharpTilo** [unity-atoms/unity-atoms#353]
**Describe the bug**
When referencing Vector2/3 the dropdown menu in the editor isnt properly displayed.

**To Reproduce**
Make a [SerializedField] for a Vector2/3Reference from a script.

**Expected behavior**
Dropdown menu should be accessible.

**Screenshots**
[How it looks in Version 4.4.5](https://i.imgur.com/eiiLyg2.png)
[How it should look from version 4.4.3](https://i.imgur.com/RAjRqKK.png)

**Environment**
 - OS: Windows10
 - Unity Version 2021.3.2f1 also 2021.2.3f1
 - Atoms 4.4.5

**Comment by MatthewBridgeman** [comment]
For anyone possible stuck on this, reverting the change [in this commit](https://github.com/unity-atoms/unity-atoms/commit/aecaa73ad0d4956a2abe6f84bbd47c615d1dd88d) has made Vector2 and Vector3 References work properly again in the editor.

I simply removed the core package dependency from my manifest.json (com.unity-atoms.unity-atoms-core@4.4.5), and then moved the package folder from Library/PackageCache/PKG_NAME to Packages/PKG_NAME.
After that I just reverted the changes from the mentioned commit and it works again.

I do not know what potential negative affects this may have, I do not understand enough about what that commit fixed in the first place.

As you can see here, it is working again:
![image](https://user-images.githubusercontent.com/37630756/175519085-79acb6c0-7d53-48df-a94b-95da94dda2d0.png)

**Comment by soraphis** [comment]
thank you for spending time investigating it, this is really helpfull!

**Comment by soraphis** [comment]
https://github.com/unity-atoms/unity-atoms/pull/359

**Comment by AdamRamberg** [comment]
Fixed in #359, which just got merged to `canary`.
