### ISSUE TITLE
[BUG] `SyncGameObjectToList` add the game object multiple times

### ISSUE THREAD

**Issue by ezaca** [unity-atoms/unity-atoms#375]
**Describe the bug**
Component `SyncGameObjectToList` is pretty intuitive in its purpose, but it happens to add the game object multiple times to the referred list, if the object is enabled and disabled at runtime.

**To Reproduce**
1. Add any game object to the scene;
2. Add the component `SyncGameObjectToList`;
3. Fill its `list` field with a valid variable;
4. Play the scene;
5. In inspector, activate and deactivate the GameObject repeteadly (you can do it by code, if you prefer).
6. Observe the game object is added again and again to the list "OnEnable".

**Expected behavior**
The game object instance should be added to the list once, instead of multiple times. I don't know why `OnEnable`/`OnDestroy` pair were used instead of `Awake`/`Destroy`, but it can fit there too with a simple "contains" check. It would be useful as well if it could handle cases where the game object is removed on disable, because *sometimes* (not always) the developer may want to remove it from the list if disabled. Could it be a bool field?

**Environment**
 - OS: Windows
 - Unity Version: 2021.3.3f1
 - Version of Unity Atoms: 4.4.5

**Additional context**

Line causing the issue:

https://github.com/unity-atoms/unity-atoms/blob/5df498b41ee77de0c5faa73b76f7fd0ed890216a/Packages/BaseAtoms/Runtime/MonoBehaviourHelpers/SyncGameObjectToList.cs#L19

**Comment by soraphis** [comment]
this is correct. it should be either `OnEnable` / `OnDisable` or `Awake` / `OnDestroy` depending on whether or not a disabled GameObject should be added to the list.

I'd argue against a Contains check since it could be costly for long lists.

Though, there is a use case in the editor, which could still result in double-assignment for `OnEnable` / `OnDisable` flow:
if you do code changes while at runtime, OnEnable will be called again after script recompilation and I think OnDisable is NOT called in this case.

**Comment by AdamRamberg** [comment]
Fixed in #389.
