### ISSUE TITLE
[FEATURE]Using different icon for each type of event

### ISSUE THREAD

**Issue by nixvalentine** [unity-atoms/unity-atoms#96]
Currently when I look at events inside atoms folder, I can't tell which event is float, vector3 or what. Even its inspector does not show the info.

If we can use different icons for each type of events, float event with "F"and, Vector3 with "V3" and so on, then this will be solved easily.

Previously I used SO Architecture and it does just as mentioned above and it works.

Hopefully we can do that soon since it seems easy.
Also, anyone can suggest an manual solution is really appreciated by me. My noobs skill can't do this by myself.
Have a nice day.

**Comment by soraphis** [comment]
while this is solvable for built-in types, it breaks for user-defined types.

a "quick fix" in the mean time: name your assets: <type><name> 

e.g.: "float_PlayerHealth"

**Comment by nixvalentine** [comment]
Thanks for your quick fix.
Though I think it would be better even if only built-in types got different corresponding icons And user-defined types have 1 specific icon for them.

**Comment by soraphis** [comment]
Vote if you wan't to see this feature added

👍 yes.
👎 no.

**Comment by miikalo** [comment]
User added types could have fields for custom icons in the generator.

**Comment by soraphis** [comment]
> User added types could have fields for custom icons in the generator.

how many users would actually use this feature? 10+ icons per type customizing.

**Comment by miikalo** [comment]
> > User added types could have fields for custom icons in the generator.
> 
> how many users would actually use this feature? 10+ icons per type customizing.

Hmm, in that case as a user I definitely wouldn't bother with it. Maybe then a color picker that colors the default icon for custom types?

**Comment by AdamRamberg** [comment]
My 2 cents is that by adding different icons for each combination of value type + Atom type will make icons cluttered and actually harder to understand, especially for new users. This is one of the reason why I just went with different icons per atom type in the first place. 

It also becomes more tedious to add new types to the library (since you need to add 10+ new icons), which is something that is already kind of a pain today. I really want to make it easier to make changes to the library, while this change will go in the opposite direction. 

Furthermore, the icon script is really a big fat hack. It’s a post processor script that is making changes to the meta files directly via file IO. It’s probably pretty slow. I guess adding more icons to it will not make it slower, but in my mind it just doesn’t feel the best to add to something that already feels broken. 

I really wish there were something built-in into Unity for marking / coloring / tagging assets in the project view.

**Comment by Narudgi** [comment]
Indeed, then it could simply be an auto rename feature as an atom option ("float_", ...), easily scalable but i dont know in for the editor performance part.

Or take some inspiration from this repo https://github.com/pointcache/unity-file-extension where we can get some clearer "marking", at least it could work as a temporary solution until unity make a feature for this one day, 

What do you think ?

**Comment by soraphis** [comment]
Closing this. as there is no intend of resolving it.
Feel free to re-open or start a discussion in the discussion tab
